### ISSUE TITLE
Unable to stop service after making SOAP request

### ISSUE THREAD

**Issue by effward** [dasMulli/dotnet-win32-service#13]
I am running a .NET Core console application as a service using this library. The application makes SOAP requests to another service using the dotnet/wcf library (https://github.com/dotnet/wcf). If the application makes any SOAP requests then it stops responding to the stop command, and when I try to stop the service I get an error "Error 1061: The service cannot accept control messages at this time.". If the application does not make any SOAP requests then it can be stopped without an issue.

If the application creates a channel like so, then it cannot be stopped.
```c#
using (var factory = new ChannelFactory<IRccService>(new BasicHttpBinding(BasicHttpSecurityMode.None), new EndpointAddress(Settings.Default.ArbiterEndpoint)))
{
    var proxy = factory.CreateChannel();
    factory.Close();
}
```
However if the following line is commented out, everything works.
```c#
var proxy = factory.CreateChannel();
```

**Comment by dasMulli** [comment]
Interestingly, i encounter a different error when doing that - (Error 109: The pipe has been ended).
I'll need to investigate further, the issue does not occur when running on full framework and also not if i copy the same code snippet before `serviceHost.Run()` - could you try doing that as well?
Also, where do you create that channel? Inside a `IWin32Service.Start()` or later?

**Comment by sichbo** [comment]
I've hit the same "Error 109: The pipe has been ended" issue. It's actually an ExecutionEngineException/Access Violation under the hood. I think a delegate is being disposed. It's just a coincidence that "doing some work" is causing a GC to kick in. 

Seems to fix it if you change Win32ServiceHost.cs line ~102:

```
serviceStatusHandle = nativeInterop.RegisterServiceCtrlHandlerExW(serviceName, HandleServiceControlCommand, IntPtr.Zero);
```

to keep a reference to the delegate..
```
private ServiceControlHandler handleServiceControlCommand;
Win32ServiceHost() 
{
 ...
 handleServiceControlCommand = new ServiceControlHandler(HandleServiceControlCommand);
 ...
}
private void ServiceMainFunction(int numArgs, IntPtr argPtrPtr)
{
   ...
   serviceStatusHandle = nativeInterop.RegisterServiceCtrlHandlerExW(serviceName, handleServiceControlCommand, IntPtr.Zero);
   ...
}
```

**Comment by dasMulli** [comment]
Thanks for looking at it! if that's it,  i'll fix it today and push a new version.

**Comment by effward** [comment]
I'm not sure, but it sounds like these might be slightly different issues. Here is a more complete repro case (sorry for not including originally).

```c#
using System;
using System.ServiceModel;
using DasMulli.Win32.ServiceUtils;

namespace ConsoleApp3
{
    public class MyService : IWin32Service
    {
        public string ServiceName => "DotNet Core Test Service";

        public static void Main(string[] args)
        {
            MakeSoapCall(); // calling it here makes it work

            var myService = new MyService();
            var serviceHost = new Win32ServiceHost(myService);
            serviceHost.Run();
        }

        public void Start(string[] startupArguments, ServiceStoppedCallback serviceStoppedCallback)
        {
            MakeSoapCall(); // if it gets called here first, service fails to stop
        }

        public void Stop()
        {
        }

        private static void MakeSoapCall()
        {
            var binding = new BasicHttpBinding(BasicHttpSecurityMode.None);
            var endpoint = new EndpointAddress("http://test.com");

            // remove this block and it works
            using (var factory = new ChannelFactory<IRccService>(binding, endpoint))
            {
                var channel = factory.CreateChannel();
                channel.GetVersion();
            }
        }
    }

    [ServiceContract(Namespace = "http://test.com/")]
    public interface IRccService
    {
        [OperationContract(Action = "http://test.com/GetVersion", ReplyAction = "*")]
        [XmlSerializerFormat]
        string GetVersion();
    }
}
```

**Comment by dasMulli** [comment]
@sichbo I just merged a fix, there is a `1.0.1-master-41` package on the feed `https://ci.appveyor.com/nuget/dotnet-win32-service` if you want to give it a try, i'll publish it to NuGet shortly when i have verified it works in my scenario.

**Comment by dasMulli** [comment]
@effward Yes i think those are different issues.
The state "Started" is reported together with the "i can now accept stop commands" info to windows *after*  the `Start(..)` function has exited. This is done so that no call to `Stop()` occurs if you haven't yet completed the startup and no "Started" state is reported if an exception is thrown from the `Start()` method or `serviceStoppedCallback()` is called within `Start()` indicating a failed startup. 
If you block that with a network request, you'll end up delaying this report and you will still be in a "Starting" state for quite a long time. You should try doing that asynchronously using APIs like `Task.Factory.StartNew(…)` or `ThreadPool.QueueUserWorkItem(…)`.

**Comment by dasMulli** [comment]
@sichbo it's on NuGet now https://www.nuget.org/packages/DasMulli.Win32.ServiceUtils/1.0.1

**Comment by sichbo** [comment]
Appreciate the effort @dasMulli ! I'm not actually using the full library though. Here's a rehash of your interop work to be a little bit thinner (1 file):

https://gist.github.com/sichbo/f169c9cf866d2ecd3cfdba307fe915d1

It'd be only 400 lines if we took out the unessential enums and just hard coded a few ints instead etc. Left in for clarity though. Usage is much the same to what you have:
```
Win32Service.TryInstallService(..)
Win32Service.TryDeleteService(..)
new Win32Service(new SomeIWin32Service()).Run();
```
Will be sure to keep you and your original project in the credits. Thanks for writing this! You are awesome.

**Comment by effward** [comment]
@dasMulli @sichbo Thanks guys! This fixed our issues as well.

**Comment by dasMulli** [comment]
@effward thanks for confirming the fix. closing this now.

@sichbo Yeah most stuff is there purely for maintainability and testing. I initially had query functionality in there as well but decided to remove it in favor of `System.ServiceProcess.ServiceController` (and didn't delete all enums/values). Nice gist, this is exactly why i like the MIT license.. just grab the code and use it for what you need without ceremony.
