### ISSUE TITLE
Track: Ship 1.1.0

### ISSUE THREAD

**Issue by dasMulli** [dasMulli/dotnet-win32-service#21]
(Tracking issue)

- [x] Write release notes
- [x] Tag release => Create GitHub release
- [x] Upload to NuGet

**Comment by thoemmi** [comment]
Hi, I'm currently using 1.1.0 from the AppVeyor feed. Is there any estimated date of publishing it to the official NuGet gallery?

BTW, thanks for sharing your great library 👍

**Comment by dasMulli** [comment]
I've had some problems finding time for it, only have one work item left to do (deprecated `RunAsync()` but all tests use it.. theoretically I could just release without it).

but It's good to know that it works for you so a better chance it'll work 👍 (I pushed support for a builder API that will allow adding new config features without blowing up the createservice() function and my mind with it)

thanks for your patience! glad you like it!

**Comment by dasMulli** [comment]
I had some trouble getting this into the main product using it very late into a release cycle and am on vacation now, but will be back next week.

**Comment by maxfuterman** [comment]
Does it's working on win 64 bit?

**Comment by dasMulli** [comment]
@maxfuterman it is architecture independent and as such works everywhere a .net standard library can work.

**Comment by dasMulli** [comment]
1.1.0 finally uploaded to NuGet and awaiting indexing.
