### ISSUE TITLE
Moving dll location from build path

### ISSUE THREAD

**Issue by MikeRavenelle** [dasMulli/dotnet-win32-service#24]
When I copy the dll from the visual studio build path to any other location and create the service using the new path (ex: C:\Program Files (x86)\Folder\ex.dll). The service never starts and times out giving error 1053. If I use the original output build path it will start correctly.

**Comment by dasMulli** [comment]
Hi!
Did you use the sample / custom application? Is it a .net core or "classic .net" application?
To create a "copyable" output, you'll need to use `dotnet publish` to make sure everything is included in the output folder that is needed to run correctly..

**Comment by MikeRavenelle** [comment]
It is a custom application and I am using .net core. 

So if I run:

`sc.exe create MyService DisplayName= "My Service" binpath= "C:\Program Files\dotnet\dotnet.exe C:\Users\Telex\Documents\Projects\Test\Test\bin\Release\netcoreapp1.0\win10-x64\Test.dll --run-as-service"`

It will start correctly.

If I move that dll anywhere else on the hard drive it will not start correctly. I will try and publish it and see if that works. Thanks!

**Comment by MikeRavenelle** [comment]
So I published and the same issue occurs. If I create the service to the publish directory it works. If I move all the files to a different location and then create a service that points to that directory it will not start.

**Comment by dasMulli** [comment]
Thanks, I'll have a look at it later.
If you register the service using `sc.exe`, you'll also need to escape the path argument after `dotnet.exe` if it contains spaces - like `Program Files` (which is why the sample has [this crazy method](https://github.com/dasMulli/dotnet-win32-service/blob/master/samples/TestService/Program.cs#L111)). (And which is also weird because the executable in `binpath` doesn't need escaping..).

**Comment by dasMulli** [comment]
@MikeRavenelle So I tried it out and it does seem like an escaping issue in the path.
Using [this sample (TestSvc.zip)](https://github.com/dasMulli/dotnet-win32-service/files/772186/TestSvc.zip), this works:
```cmd
> dotnet restore && dotnet publish
> cd C:\Program Files (x86)\TestSvc
> xcopy \Users\martin.ullrich\Documents\TestSvc\bin\Release\netcoreapp1.0\publish  .
\Users\martin.ullrich\Documents\TestSvc\bin\Release\netcoreapp1.0\publish\DasMulli.Win32.ServiceUtils.dll
\Users\martin.ullrich\Documents\TestSvc\bin\Release\netcoreapp1.0\publish\TestSvc.deps.json
\Users\martin.ullrich\Documents\TestSvc\bin\Release\netcoreapp1.0\publish\TestSvc.dll
\Users\martin.ullrich\Documents\TestSvc\bin\Release\netcoreapp1.0\publish\TestSvc.pdb
\Users\martin.ullrich\Documents\TestSvc\bin\Release\netcoreapp1.0\publish\TestSvc.runtimeconfig.json
5 File(s) copied

> sc.exe create TestSvc DisplayName= TestSvc binpath= "C:\Program Files\dotnet\dotnet.exe \"C:\Program Files (x86)\TestSvc\TestSvc.dll\""
[SC] CreateService SUCCESS
```

If I drop the `\"` surrounding the dll path, I get the exact same error you mentioned (1053).

**Comment by MikeRavenelle** [comment]
That works! Thank you very much. I had tried that escape in powershell where it does not work. in command prompt it does work.
