### ISSUE TITLE
Can you add the possibility of install the service with Delayed Autostart?

### ISSUE THREAD

**Issue by jersiovic** [dasMulli/dotnet-win32-service#25]
In the mean time I use sth like this through a powershell script http://metah.ch/blog/2012/09/how-to-change-a-service-startup-type-with-powershell/

**Comment by dasMulli** [comment]
Will keep that in mind, i already use `ChangeServiceConfig2()` for the description so a second call using `SERVICE_CONFIG_DELAYED_AUTO_START_INFO` as `dwInfoLevel` should do it. passing a pointer to a bool should be enough looking at the `SERVICE_DELAYED_AUTO_START_INFO ` structure. (basically making notes to myself here..)
