### ISSUE TITLE
ServiceState enum mispelling

### ISSUE THREAD

**Issue by sethrudesill** [dasMulli/dotnet-win32-service#32]
I believe "StartPening" should be "StartPending"

https://github.com/dasMulli/dotnet-win32-service/blob/master/src/DasMulli.Win32.ServiceUtils/ServiceState.cs

**Comment by sethrudesill** [comment]
Is this ever going to get fixed? I have a friend using this.

**Comment by dasMulli** [comment]
Sadly this would now be a breaking change 😢 
but I guess it is worth the change and simple to fix in consuming code.

I was planning to invest some time for a few other changes and multi-target to netstandard2.0 when it hits.
I'll make the change later today and see when it makes sense to publish a new public version.

**Comment by dasMulli** [comment]
A build containing the change is available on the `https://ci.appveyor.com/nuget/dotnet-win32-service` feed as version `1.1.0-master-000063`

**Comment by sethrudesill** [comment]
The beauty and danger of System.Enum is that if you explicitly assign each enum field an integer, you can have multiple items with the same value. You could apply the "deprecated" attribute to StartPening with "force compiler error" turned on, give StartPending the same value as StartPening, and then later remove the enum misspelling once you've deemed enough time has passed.
