### ISSUE TITLE
Can't serve static files out of wwwroot

### ISSUE THREAD

**Issue by jeremywho** [dasMulli/dotnet-win32-service#40]
I've got an asp.net core 2.0 app and I've added in your service helpers. I can run the app/register the service, everything seems fine, but...

And I'm sure this is something I'm doing wrong, but I've got a directory under wwwroot that I'm serving static files from. When I debug the app or run it from the publish directory, everything works fine.  But, when I run it as a service, the files from that directory (under wwwroot) are not found.  Other MS sample files can be found, but not the ones I've added.  I can see them under the publish folder, but they aren't getting served.

Any idea what this may be?  The only reason I'm posting here is because it only happens when running as a service.

**Comment by jeremywho** [comment]
Closing this, `.UseContentRoot` needs to be set correctly, otherwise it defaults to `C:\Windows\system32` when running as a service.

**Comment by dasMulli** [comment]
I'm glad you figured it out.
However, I should update the samples to the 2.0 hosting model and maybe add razor pages or even a full mvc sample..

**Comment by jeremywho** [comment]
@dasMulli Awesome, thanks.
