### ISSUE TITLE
The service process could not connect to the service controller

### ISSUE THREAD

**Issue by Antaris** [dasMulli/dotnet-win32-service#56]
Hi,

I'm utilising a signed version of your project to host some distributed services as Win32 services. The integration works fine, but when I try and run the project from VS, or from the command prompt, I keep getting the same result:

> The service process could not connect to the service controller

Literally the only thing I have changed is to sign the code (we have an internal policy about code signing), and have deployed it to our internal NuGet package feed.

OS: Windows 10 (1607 - 14393.1944)
.NET Core version: 2.0.0

Sounds like it is having issues with the following error code - `ERROR_FAILED_SERVICE_CONTROLLER_CONNECT`? This seems to be an intrinsic error when running a service as a console app - I'm not sure how to tell Windows otherwise :-/

**Comment by dasMulli** [comment]
If you run from the command line, you mustn’t call the Run method on the service host. The sample configures the service registration to pass “—run-as-service” as a command line argument.
This is similar to checking Environment.UserInteractive before calling ServiceBase.Run() in classic .net services, just that this property returns a fixed value on core.

**Comment by Antaris** [comment]
For your projects, are you targeting a specific runtime, or can you still be portable?

**Comment by dasMulli** [comment]
self-contained netcoreapp.
Shouldn't matter though

**Comment by dasMulli** [comment]
fyi TopShelf checks if the parent process is named `services` to check if running "user interactive" or via service management. Couldn't get myself to switch to that though - it scares me.

https://github.com/Topshelf/Topshelf/blob/956325c8104136af7e8f8fc708b6237668d1c55c/src/Topshelf/Runtime/Windows/WindowsHostEnvironment.cs#L142-L147

**Comment by Antaris** [comment]
Right, based on your guidance I think I've got this working. Had to implement the command-line controls, to handle registration etc. So it's now working from the command line using `--interactive`, however it won't run as a windows service, just sits in the starting state for ages.

**Comment by dasMulli** [comment]
It needs to return from the Start() method to notify the service controller of the completed startup. If you block inside the service start, it will hang and eventually time out.

**Comment by Antaris** [comment]
Bingo! Thanks for your help dude, massive props! :-D
