### ISSUE TITLE
Provide an Extension to IWebHost

### ISSUE THREAD

**Issue by Trapov** [dasMulli/dotnet-win32-service#57]
First of all thank you for the project, you saved me a lot of time.

_Problem_: I want to run my ASP.NET Core as a service, but examples are so big, they don't give an idea how to simple configure it and run. 

So what i suggest is an **IWebHost** extension, that's just easy to set-up. Kinda an analogy to this:

https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting.WindowsServices/WebHostWindowsServiceExtensions.cs

**Comment by dasMulli** [comment]
Implemented by #58 and #59
