### ISSUE TITLE
IWebHost extension

### ISSUE THREAD

**Issue by jpmnteiro** [dasMulli/dotnet-win32-service#61]
Hey,

I've added a reference to the latest [nuget package](https://www.nuget.org/packages/DasMulli.Win32.ServiceUtils/) available but there isn't a reference to `RunAsService(...)`. Are you planning on releasing a package soon with that extension method?

**Comment by dasMulli** [comment]
I wanted to have a look at #60 first, which would also reduce the samples. but yes, I do plan on doing that soon.

in the meantime, the classic samples are a few commits earlier: https://github.com/dasMulli/dotnet-win32-service/tree/c857075e66af164b2f231b0faf6ff5cc6ad7f4b8/samples/MvcTestService

**Comment by sebitsi** [comment]
@dasMulli 
Hi Martin.

Do you have any plans to releasing new package ?

**Comment by dasMulli** [comment]
It is now available on NuGet
