### ISSUE TITLE
Use PInvoke package for native functions

### ISSUE THREAD

**Issue by NN---** [dasMulli/dotnet-win32-service#77]
Package: https://www.nuget.org/packages/PInvoke.AdvApi32

Repository: https://github.com/AArnott/pinvoke/

**Comment by dasMulli** [comment]
@NN--- is there an exact improvement you are suggesting here?
The intent was to keep dependencies and API surface to the minimum. Also, they target desktop frameworks and thus cannot be used on platforms without netfx asset target framework compatibility (<ns2.0)

**Comment by dasMulli** [comment]
Closing due to discussion not being followed up.
