### ISSUE TITLE
Windows could not stop service, using IWin32ServiceStateMachine

### ISSUE THREAD

**Issue by TheColonel2688** [dasMulli/dotnet-win32-service#82]
So I have implemented an IWin32ServiceStateMachine. my goal is to allow time for my program to gracefully exit. however, keep getting an error "Windows could not stop the <My Service> service"

I have a Task.Delay(15000) in my OnStopPending() in my service implementation class. This is to simulate a long shutdown.

Stop is now called by the serviceImplemenation using a delegate.

here is my code. 

Am I doing this correctly

```
// <summary>
/// Called by the service host when a command was received from Windows' service system.
/// </summary>
/// <param name="command">The received command.</param>
/// <param name="commandSpecificEventType">Type of the command specific event. See description of dwEventType at https://msdn.microsoft.com/en-us/library/windows/desktop/ms683241(v=vs.85).aspx </param>
public void OnCommand(ServiceControlCommand command, uint commandSpecificEventType)
{
	if (command == ServiceControlCommand.Stop)
	{
		statusReportCallback(ServiceState.StopPending, ServiceAcceptedControlCommandsFlags.None, win32ExitCode: 0, waitHint: 15000);

			serviceImplementation.OnStopPending();
	   

		}

		//statusReportCallback(ServiceState.Stopped, ServiceAcceptedControlCommandsFlags.None, win32ExitCode, waitHint: 0);
	}
}

public void Stop(int win32ExitCode)
{
	statusReportCallback(ServiceState.Stopped, ServiceAcceptedControlCommandsFlags.None, win32ExitCode, waitHint: 0);
}
```

Shared Code between the 2 methods

    StartupLogger.Debug("Running As a Service");
    CancellationTokenSource source = new CancellationTokenSource();
    CancellationToken token = source.Token;

    var theTask = new Task(() =>
    {
        Task.Delay(10000, token).Wait();
        StartupLogger.Debug($"Done Waiting, Was Canceled = {token.IsCancellationRequested}");
        StartupLogger.Debug("_______________");
    });

this my Code For OnStart

    StartupLogger.Debug("Service Started");
    StartupLogger.Debug("_______________");
    StartupLogger.Debug($"Start theTask");
    theTask.Start();
    StartupLogger.Debug("Service Startup Done");

This my Code for OnStop

    StartupLogger.Debug("Service Stop Called");
    StartupLogger.Debug("_______________");
    StartupLogger.Debug($"theTask status  = {theTask.Status}");

    source.Cancel();
    StartupLogger.Debug("Cancel Called");
    StartupLogger.Debug("_______________");
    StartupLogger.Debug($"Waiting for theTask to complete");
    theTask.Wait(); //** Service Throws Error while waiting here

    StartupLogger.Debug("Service Stop Done");

    //** Tell Service Host to Stop
    self.Stop(0);

    StartupLogger.Debug("Service Stop Done Done");

    Log.Logger = StartupLogger;
    Log.CloseAndFlush();

**Comment by TheColonel2688** [comment]
@dasMulli

**Comment by dasMulli** [comment]
What error is thrown? (exception?)
E.g. you're not catching `OperationCancelledException` which could make the app terminate without reporting a status to the service host.
Do you have a complete runnable example to try out?

**Comment by TheColonel2688** [comment]
![image](https://user-images.githubusercontent.com/8753759/61808189-f0891d80-ae08-11e9-947f-4f6d42c8141d.png)


[https://drive.google.com/file/d/18vyrmM-Riy8ABDHvB5o0-U6l2ZfSgg9G/view?usp=sharing](https://drive.google.com/file/d/18vyrmM-Riy8ABDHvB5o0-U6l2ZfSgg9G/view?usp=sharing)

There is a runable solution in the zip at that link.

**Comment by TheColonel2688** [comment]
Sorry, not catching the `OperationCancelledException` seems to be the issue. I also had to do a clean and a rebuild for the changes to take effect after I added the try-catch. Which is odd.

Sorry for wasting your time.
